# Generated by Django 4.2.1 on 2023-05-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_price', models.CharField(max_length=150)),
                ('P_iamge', models.CharField(max_length=150)),
                ('Model_no', models.CharField(max_length=50)),
                ('P_ram', models.EmailField(max_length=254, unique=True)),
                ('P_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
