# Generated by Django 4.2.1 on 2023-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sub',
            old_name='P_iamge',
            new_name='P_image',
        ),
        migrations.AlterField(
            model_name='product_sub',
            name='P_ram',
            field=models.IntegerField(unique=True),
        ),
    ]
